fruit=[]
f1=input("enter a frout name:")
fruit.append(f1)
f2=input("enter a frout name:")
fruit.append(f2)
f3=input("enter a frout name:")
fruit.append(f3)
f4=input("enter a frout name:")
fruit.append(f4)
f5=input("enter a frout name:")
fruit.append(f5)
f6=input("enter a frout name:")
fruit.append(f6)
print(fruit)
fruit.sort()
print(fruit)