s={}
name=(input("Enter friend namae: "))
lang=input("Enter language name: ")
s.update({name:lang})
name=input("Enter friend namae: ")
lang=input("Enter language name: ")
s.update({name:lang})
name=input("Enter friend namae: ")
lang=input("Enter language name: ")
s.update({name:lang})
name=input("Enter friend namae: ")
lang=input("Enter language name: ")
s.update({name:lang})
print(s)